import Header from '@/components/Header'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const Nunito = Nunito_Sans({ subsets: ['latin'], weight : ['200' , '300' , '400' , '500' , '600' , '700' , '800' , '900' , '1000'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-lightbg text-darkblue dark:text-white  dark:bg-darkbg w-screen h-screen ${Nunito.className}`}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
